# -*- coding: utf-8 -*-
"""Preprocess_Tracking_Data_JH.ipynb

Automatically generated by Colab.

Original file is located at
    google link for where the files are stored
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import pandas as pd

conditions = ['odor_1, 'odor_2'] #Change to whatever data your inputting 
days = ['D1', 'D2', 'D3']

list_of_filepaths =['filepath']

for filepath in list_of_filepaths:
  path_to_preprocessed = os.path.join(filepath, 'preprocessed')
  try:
    os.mkdir(path_to_preprocessed)
  except OSError as error:
    pass
  for condition in conditions:
    path_to_pre_cond = os.path.join(path_to_preprocessed, condition)
    try:
      os.mkdir(path_to_pre_cond)
    except OSError as error:
      pass
    for day in days:
      path_to_pre_cond_day = os.path.join(path_to_pre_cond, day)
      try:
        os.mkdir(path_to_pre_cond_day)
      except OSError as error:
        pass
  #make the pre combined folder
  path_to_preprocessed_combined = os.path.join(filepath, 'preprocessed combined')
  try:
    os.mkdir(path_to_preprocessed_combined)
  except OSError as error:
    pass
  for condition in conditions:
    path_to_pre_comb_cond = os.path.join(path_to_preprocessed_combined, condition)
    try:
      os.mkdir(path_to_pre_comb_cond)
    except OSError as error:
      pass
  for day in days:
    path_to_pre_comb_cond_day = os.path.join(path_to_pre_comb_cond, day)
  try:
    os.mkdir(path_to_pre_comb_cond_day)
  except OSError as error:
    pass
  path_to_bouts = os.path.join(filepath, 'Bouts')
  try:
    os.mkdir(path_to_bouts)
  except OSError as error:
    pass
  for condition in conditions:
    path_to_bout_cond = os.path.join(path_to_bouts, condition)
    try:
      os.mkdir(path_to_bout_cond)
    except OSError as error:
      pass

# Read raw file and return pandas dataframe
def read_raw(file_path):
  return pd.read_csv(file_path, sep='\t', header=None, names=['time', 'x', 'y', 'in', 'entry', 'exit'])

# Standarize the y-coordinates.
# y >= 0 indicate how far animal is in ROSA while y < 0 indicate how far animal is in RONSA
def adjust_y(df):
  border = df[df['entry'] == 1]['y']
  if len(border) > 0:
    df['y'] = max(border) - df['y']
  else:
    df['y'] = 235 - df['y']  # if the fly never entered ROSA, use upper-bound estimate

# Standardize the x-coordinates
# def adjust_x(df):
#   mid = ((df['x'].max() - df['x'].min())/2) + df['x'].min()
#   df['x'] = df['x'] - mid

# Read, subset, and standardize y-coordinate for a raw file
def read_adjust(file_path):
  df = read_raw(file_path)
  df = df[df['time'] >= 1]
  adjust_y(df)
  # adjust_x(df)
  return df

"""# Preprocess"""

folder_path = 'filepath' #change this to the directory for your data

for condition in conditions:
  for day in days:
    temp_path = os.path.join(folder_path, condition, day)
    print(temp_path)
    for a_file in os.listdir(temp_path):
      print(a_file)
      if a_file.endswith('.txt'):
        temp_df = read_adjust(os.path.join(temp_path, a_file))
        temp_df.to_csv(f'filepath and name.csv', index=False)

"""# Combined the Preprocessed Data"""

folder_path = 'filepath'

for condition in conditions:
  for day in days:
    temp_path = os.path.join(folder_path, condition, day)
    print(temp_path)
    df = pd.DataFrame(columns=['time', 'x', 'y', 'in', 'entry', 'exit', 'id'])
    for a_file in os.listdir(temp_path):
      print(a_file)
      temp = pd.read_csv(os.path.join(temp_path, a_file))
      temp['id'] = a_file#[a_file.rfind('-')+1:-6] #if not 13, then 12. was -7
      df = pd.concat([df, temp], ignore_index=True)
      #print(df.tail())
    df.to_csv(f'filepath and name.csv', index=False)

"""# Bouts"""

def get_bouts(df):
  """
  Creates a pandas dataframe with bouts data for a singular fly
  """
  indices = np.sort(np.concatenate([0, np.where(df['entry'] == 1)[0], np.where(df['exit'] == 1)[0], df.shape[0]-1], axis=None))

  bouts = pd.DataFrame(columns=['bout', 'in', 'start', 'end', 'depth', 'distance'])
  for i in range(indices.size-1):
    start, end = indices[i], indices[i+1]
    if end - start > 1:  # make sure this bout is greater than 1 frame, otherwise ignore
      depth = np.amax(np.abs(df.loc[start:end-1, 'y'])) #Why are you calculating depth this way?
      dist = np.sum(np.sqrt(np.sum(np.square(np.subtract(df.iloc[start+1:end-1][['x', 'y']].reset_index(drop=True), df.iloc[start:end-2][['x', 'y']].reset_index(drop=True))), axis=1)))
      bouts.loc[bouts.shape[0]] = [i, df.iloc[start]['in'], df.iloc[start]['time'], df.iloc[end-1]['time'], depth, dist]
  #print(len(indices))
  return bouts

def get_combined_bouts(df):
  """
  Creates a pandas dataframe with bouts data for all flies in a day
  """
  flies = df['id'].unique()

  bouts_days = pd.DataFrame()
  for fly in flies:
    bouts_ind = get_bouts(df[df['id'] == fly].reset_index(drop=True))
    bouts_ind['id'] = fly
    bouts_days = pd.concat([bouts_days, bouts_ind], ignore_index=True)

  return bouts_days

for condition in conditions:
  print(condition)
  for day in days:
    print(day)
    temp = pd.read_csv(f'file path and name.csv')
    combined_bouts = get_combined_bouts(temp)
    combined_bouts.to_csv(f'file path and name.csv', index=False)
  print()